language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
after_success:
  "find ./build -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://pedak.me/proc/messing/{} \;"
env:
  global:
  - secure: XJ4+KZWo4nPBiO5GivG0hhspEggGVv0R3FQizT1Y45Ea+RtLRmuQ77oILrjCxgsZFARyMb15YxOuSWUGUawXbXYQw1J/hBii7UaYnso/OHzKW8jvN3Gd0vHKftLt2+wjx+yOl1M9oTc89KvIEp//uN5TAo/f1pTeMHA+I6z26KAcMBu2Ie4BIp4m0oVT4c67+FzQnOZgmIDx4PbGqcsuAQnDSBwjDjXuONhW318eNOwWV9RPoNGt36EZSQ1TvVBhtm8xFhPx/FF9dA7CaEBchwwz8Juo/KUupz54Y91ZbASOQnwY9FRTVV1XnQDC3M8aAIHmphevvV1OoEBtXaswM+2wYfNu+sgK4xOUYAMTZ61K17rNlrA/pHX5aSpuX3KCIZS7+BQGjtf2WjJ/zE0Zu7DiO2SXmB3IRg1Pz6GTnEWWCQf4FoUnoOfBPvpvz1jmriJ4r0zQCSAKUBp3y6xaT7sxnXBBodfx0YAHqquOmTBaLhfuEkLmXBoOT8xyuYLb8TzGBnigpvjvTXB4QAcQf/46suL3FeMA/txsJ6kGtEjEPnv9QnBNw4lAVcXFxj7Wq2pXlCgu6cIm6rTqpcgPQgXUh30gDglWRaJ9vOcQImSfZSWulyJO3+51iOkOaMui0p6S6sVpuxOYgtA+apGFaBwHu8zkN+lovJnTzR3B8Zc=
  - secure: 0y9VgaxEB25e1/bfl1T6nx2vvkDIF2Wb1H3gkJNDqwvHe7QBBPH5RjpdpftEMPb+6afdbaB0qc/G1lJome9iilWxTTNaK+Q6KZymW0PyV7+mm1UMSCrXqII1ffJdFAXgNspMLU35DtDwWqAUsxM/OKtpyIXrVwNs+WSaClnDrYgnD5iAoRpSHd835ZQo58VSYoYrH3YXNtDFu9qKwWmPxJSMYvjZ1XzPHSMY91V5SO3HB+TyxobKSZCiWQ3uSmpoFjOrVK5/FmvHsJStbLnA4y0pOZehQaQCwBOND7HLBBl05l4WY3GDLDJcSgj9R8JOFu9EV1msdHmEjVwbH0aExRklb4S/Sr0U+ae6L8wkuMw2pS4aUsoeC3hYOmWCmoOhhrn4uBwvdk3AgoSjDej/YD/JIWk/dQYW8G0lCB1mxQQRLFq9WzJLXdKQ1Cc9WWJ7v9pzTlbLDnsusBUGPAR6SjTl0upZXynAHIR7+k4bpU6ZnGdkOmwYQ4SnyoaR2pqdJwxQVMloERH1Uk59uRT6HqjbuWha9P3GKqtm2+hHq3DJtv+5EJo2XKkihI6omYUS9PZHhU16cmCjx6htx8YzpQx/oqKqWA+AKbI2dNaKtSUti2fxuCk7nczooaT/7HF7zKvKC9BNF2aPJj13SHytxLcnuZBzAWnEJunjSC7tTNg=
